require('dotenv').config();

function mapPresence(val) {
    const mapping = {
        typing: 'composing',
        online: 'available',
        recording: 'paused',
        paused: 'paused',
        offline: 'unavailable'
    };
    return mapping[val?.toLowerCase()?.trim()] || 'paused';
}

module.exports = {
    prefixes: process.env.PREFIX
        ? process.env.PREFIX.split(',').map(p => p.trim())
        : ['.'],

    NUMBER: process.env.YOUR_NUMBER || '254768421673',
    MODE: (process.env.MODE || 'private').toLowerCase().trim(),
    WARN_LIMIT: process.env.WARNINGS || '3',
    ON: process.env.YOUR_NAME || 'pius',
    ANTICALL: process.env.ANTICALL || 'on',
    ADM: process.env.ANTIDELETE || 'on',
    AR: process.env.AUTO_REACTION || 'off',

    AUTO_VIEW_STATUS: process.env.AUTO_READ_STATUS === 'on',
    AUTO_LIKE: process.env.AUTO_LIKE === 'on',
    AUTO_READ_MESSAGES: process.env.AUTO_READ_DM === 'on',
    HEROKU_API_KEY: process.env.HEROKU_API_KEY,
    HEROKU_APP_NAME: process.env.HEROKU_APP_NAME,
    sessionBase64: process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZU1hVStLbUpkaEdPUnppeEFDUWVRbkwxTGpxRlhvT0VidnVjT3kwZGtVUT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiRkpHZG5LZnExcXg3ZTAyVDNTUzJ4a2hKUGdjVEk1N2JVREkzUmpqbnlndz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJXRGNESStiMnRjK2FPbW1pTmFkY3RaU29oVjRUQ2tsMGJrOE0xTVdldGs0PSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJPRTZTMFRtcm9UY2RrS1hnc2E0bnE2MTYzamtwMVNjM0hudHlCU2YxSVRZPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkFGckFZOTlSVTVwZmFhUmp3ZU43WUxGbmpxZENlZU1aQkx3YTVZZWRDRWs9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjE4bkJDenFyQTJxbkNKeExrU2VtL3U2b1h3SGhRY0RJZFhyRkhybm5qa2s9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZUR5REg5MisrU1lrY1lLVVJLOUczTUlYQWpzYjJPVnh6N3FiTi9VSDlHOD0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoickg4WGhiOThBNUs0R0hyaWVwN2JhWEV4TVZlbUdYVHdkZENLWE5ZSEIwUT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjlhYXBES0p1TERFWE1HbllpczgwRUdiT0NzdzBJTzVLa05aT0RQNHR3N2x1NlNjVDdpckI4dk1uVzVheDdlT3lJcUJKNi9nWFA0RUU5dU9MbHhHamdBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTE0LCJhZHZTZWNyZXRLZXkiOiJxa05LMmIyR05NS2xFc0VqUkZjS2VGTHZvSDlvd2V5b0FRaHRka3JQSXYwPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjI1NDc2ODQyMTY3M0BzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiI0QzA0NUM4NUU2MjU2OENFNUQyMEQ5ODIyNjJDNjAxNyJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzUyMDg4ODA1fSx7ImtleSI6eyJyZW1vdGVKaWQiOiIyNTQ3Njg0MjE2NzNAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiODYzMjlGNjc1NUU2OUZENkIxQjRBN0RFNzJGOTUxRDQifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc1MjA4ODgxN31dLCJuZXh0UHJlS2V5SWQiOjMxLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzEsImFjY291bnRTeW5jQ291bnRlciI6MSwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sInJlZ2lzdGVyZWQiOnRydWUsInBhaXJpbmdDb2RlIjoiUE1aOEpCQVIiLCJtZSI6eyJpZCI6IjI1NDc2ODQyMTY3MzoxOEBzLndoYXRzYXBwLm5ldCIsImxpZCI6IjE1MjMwNjI1MTIwNDEzOjE4QGxpZCIsIm5hbWUiOiJwaXVzIn0sImFjY291bnQiOnsiZGV0YWlscyI6IkNQUGFqSlVCRU15QnU4TUdHQVlnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiIvaWJKT25IbDF2OHphQ1BJdklOMXhaZVVZM2s4MVkxRFhOWk4rNERBNFFRPSIsImFjY291bnRTaWduYXR1cmUiOiJCY1BFK2hsS0NNdTdCQ0lRSkhVMTdJUkQ1Ny8zOEpRU1liUWMyOE5zZlg1Zk9tVzZZYVlNbjdQRDhsTDM5NTBNQkV3eHRYZUxqQURXVUdHaWthV05EUT09IiwiZGV2aWNlU2lnbmF0dXJlIjoiNDFSVW4vSWtpLzJLMGFSKzJHaUpxS01IaTdSR2NkMEdKK3VIbjM5S3orUi8wZlNpMjBaMElxU3NtKzIvYVdkSWg3MW4vdDRRRHlxdEIvNjI5bldraFE9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyNTQ3Njg0MjE2NzM6MThAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCZjRteVRweDVkYi9NMmdqeUx5RGRjV1hsR041UE5XTlExeldUZnVBd09FRSJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsInJvdXRpbmdJbmZvIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQ0FVSUFnPT0ifSwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzUyMDg4NzkzLCJsYXN0UHJvcEhhc2giOiIyVjc3cVUiLCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQUNCNCJ9',
    timezone: 'Africa/Nairobi',

    USER_LID: process.env.YOUR_LID || null,

    PRESENCE_DM: mapPresence(process.env.PRESENCE_DM || 'typing'),
    PRESENCE_GROUP: mapPresence(process.env.PRESENCE_GROUP || 'recording'),

    mapPresence
};
